#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// ───────── 音频 ─────────
#define AUDIO_INPUT_SAMPLE_RATE   16000
#define AUDIO_OUTPUT_SAMPLE_RATE  24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX
// INMP441 麦克风
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
// MAX98357A 喇叭功放
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16
#endif

// ───────── LED ─────────
#define BUILTIN_LED_GPIO        GPIO_NUM_48

#if CONFIG_MY_VOICE_DISPLAY_SPI_LCD
// Carrier board (bread-compact-wifi-lcd pinout)
#define BOOT_BUTTON_GPIO        GPIO_NUM_2
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_38
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_39

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_MOSI_PIN      GPIO_NUM_47
#define DISPLAY_CLK_PIN       GPIO_NUM_21
#define DISPLAY_DC_PIN        GPIO_NUM_40
#define DISPLAY_RST_PIN       GPIO_NUM_45
#define DISPLAY_CS_PIN        GPIO_NUM_41

#define LCD_TYPE_ST7789_SERIAL
#if CONFIG_MY_VOICE_LCD_ST7789_240X320
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#else
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#endif
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#else
// Breadboard OLED
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SDA_PIN GPIO_NUM_41
#define DISPLAY_SCL_PIN GPIO_NUM_42
#define DISPLAY_WIDTH   128

#if CONFIG_OLED_SSD1306_128X32
#define DISPLAY_HEIGHT  32
#elif CONFIG_OLED_SSD1306_128X64
#define DISPLAY_HEIGHT  64
#elif CONFIG_OLED_SH1106_128X64
#define DISPLAY_HEIGHT  64
#define SH1106
#else
#error "OLED display type is not selected"
#endif

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#endif

// ───────── Camera (not connected) ─────────
#define CAMERA_PIN_PWDN    GPIO_NUM_NC
#define CAMERA_PIN_RESET   GPIO_NUM_NC
#define CAMERA_PIN_XCLK    GPIO_NUM_NC
#define CAMERA_PIN_SIOD    GPIO_NUM_NC
#define CAMERA_PIN_SIOC    GPIO_NUM_NC
#define CAMERA_PIN_D7      GPIO_NUM_NC
#define CAMERA_PIN_D6      GPIO_NUM_NC
#define CAMERA_PIN_D5      GPIO_NUM_NC
#define CAMERA_PIN_D4      GPIO_NUM_NC
#define CAMERA_PIN_D3      GPIO_NUM_NC
#define CAMERA_PIN_D2      GPIO_NUM_NC
#define CAMERA_PIN_D1      GPIO_NUM_NC
#define CAMERA_PIN_D0      GPIO_NUM_NC
#define CAMERA_PIN_VSYNC   GPIO_NUM_NC
#define CAMERA_PIN_HREF    GPIO_NUM_NC
#define CAMERA_PIN_PCLK    GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
